# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pynput.keyboard import Key, Listener
import utils
import drawbot
import threading

try:
    # Include in try/except block if you're also targeting Mac/Linux
    from PyQt5.QtWinExtras import QtWin
    myappid = 'v2f.drawbot.1'
    QtWin.setCurrentProcessExplicitAppUserModelID(myappid)
except ImportError:
    pass

class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(299, 613)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 300, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.title.setStyleSheet("font-weight:bold;")
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.urlTextBox = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.urlTextBox.setText("")
        self.urlTextBox.setObjectName("urlTextBox")
        self.verticalLayout.addWidget(self.urlTextBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.appLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.appLabel.setStyleSheet("")
        self.appLabel.setObjectName("appLabel")
        self.verticalLayout.addWidget(self.appLabel)
        self.appBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.appBox.setObjectName("appBox")
        self.appBox.addItem("")
        self.appBox.addItem("")
        self.appBox.addItem("")
        self.verticalLayout.addWidget(self.appBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.speedLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.speedLabel.setObjectName("speedLabel")
        self.verticalLayout.addWidget(self.speedLabel)
        self.speedSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.speedSlider.setMinimum(1)
        self.speedSlider.setMaximum(4)
        self.speedSlider.setProperty("value", 3)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName("speedSlider")
        self.verticalLayout.addWidget(self.speedSlider)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.skippedPixelsLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.skippedPixelsLabel.setObjectName("skippedPixelsLabel")
        self.verticalLayout.addWidget(self.skippedPixelsLabel)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setStyleSheet("font-size: 10px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.skippedPixelSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.skippedPixelSlider.setMinimum(1)
        self.skippedPixelSlider.setMaximum(12)
        self.skippedPixelSlider.setSingleStep(1)
        self.skippedPixelSlider.setProperty("value", 5)
        self.skippedPixelSlider.setOrientation(QtCore.Qt.Horizontal)
        self.skippedPixelSlider.setObjectName("skippedPixelSlider")
        self.verticalLayout.addWidget(self.skippedPixelSlider)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ignorePixelBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.ignorePixelBox.setObjectName("ignorePixelBox")
        self.horizontalLayout.addWidget(self.ignorePixelBox, 0, QtCore.Qt.AlignHCenter)
        self.ditherBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.ditherBox.setObjectName("ditherBox")
        self.horizontalLayout.addWidget(self.ditherBox, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.coordinateButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.coordinateButton.setObjectName("coordinateButton")
        self.verticalLayout.addWidget(self.coordinateButton)
        self.MouseCoordinateLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.verticalLayout.addWidget(self.MouseCoordinateLabel, 0, QtCore.Qt.AlignHCenter)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.setBoundsButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.setBoundsButton.setObjectName("setBoundsButton")
        self.verticalLayout.addWidget(self.setBoundsButton)
        self.widthLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.widthLabel.setObjectName("widthLabel")
        self.verticalLayout.addWidget(self.widthLabel, 0, QtCore.Qt.AlignHCenter)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.drawButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 134, 22))
        gradient.setColorAt(1.0, QtGui.QColor(0, 74, 26))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 134, 22))
        gradient.setColorAt(1.0, QtGui.QColor(0, 74, 26))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 134, 22))
        gradient.setColorAt(1.0, QtGui.QColor(0, 74, 26))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 134, 22))
        gradient.setColorAt(1.0, QtGui.QColor(0, 74, 26))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 134, 22))
        gradient.setColorAt(1.0, QtGui.QColor(0, 74, 26))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 134, 22))
        gradient.setColorAt(1.0, QtGui.QColor(0, 74, 26))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 134, 22))
        gradient.setColorAt(1.0, QtGui.QColor(0, 74, 26))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 134, 22))
        gradient.setColorAt(1.0, QtGui.QColor(0, 74, 26))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 134, 22))
        gradient.setColorAt(1.0, QtGui.QColor(0, 74, 26))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.drawButton.setPalette(palette)
        self.drawButton.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 134, 22, 255), stop:1 rgba(0, 74, 26, 255));\n"
"font-weight: bold;\n"
"color: white;\n"
"height: 30px;\n"
"")
        self.drawButton.setObjectName("drawButton")
        self.verticalLayout.addWidget(self.drawButton)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.errorLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.errorLabel.setStyleSheet("color: rgb(170, 0, 0);\n"
"font-weight: bold;\n"
"")
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 299, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Custom values
        self.width = 0
        self.height = 0
        self.startPosition = (0, 0)
        self.ignorePixels = False
        self.dither = False
        self.speed = 3
        self.pixelInterval = 5
        self.url = ""
        self.app = 0
        self.colors, self.coordinates = utils.getPalette(self.app)
        self.drawingThread = None

        # Signals
        self.coordinateButton.clicked.connect(self.displayMouseCoordinates)
        self.setBoundsButton.clicked.connect(self.setBounds)
        self.ditherBox.clicked.connect(self.setDither)
        self.ignorePixelBox.clicked.connect(self.setIgnorePixel)
        self.speedSlider.valueChanged.connect(self.setSpeed)
        self.skippedPixelSlider.valueChanged.connect(self.setPixelInterval)
        self.appBox.currentIndexChanged.connect(self.setApp)
        self.urlTextBox.textChanged.connect(self.setUrl)
        self.drawButton.clicked.connect(self.draw)

        # Collect keyboard events
        listener = Listener(
            on_press=self.on_press)
        listener.start()


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DrawBot"))
        MainWindow.setWindowIcon(QtGui.QIcon('drawbot.ico'))
        self.title.setText(_translate("MainWindow", "DrawBot par @IV2FI"))
        self.urlTextBox.setPlaceholderText(_translate("MainWindow", "Url de l\'image à dessiner"))
        self.appLabel.setText(_translate("MainWindow", "Sur quoi vais-je dessiner ?"))
        self.appBox.setItemText(0, _translate("MainWindow", "Gartic Phone"))
        self.appBox.setItemText(1, _translate("MainWindow", "Skribbl"))
        self.appBox.setItemText(2, _translate("MainWindow", "Paint"))
        self.speedLabel.setText(_translate("MainWindow", "Vitesse"))
        self.skippedPixelsLabel.setText(_translate("MainWindow", "Pixels ignorés"))
        self.label_4.setText(_translate("MainWindow", "Moins on en ignore, plus c\'est précis (mais lent)"))
        self.ignorePixelBox.setText(_translate("MainWindow", "Ignorer pixels isolés"))
        self.ditherBox.setText(_translate("MainWindow", "Dither"))
        self.coordinateButton.setText(_translate("MainWindow", "Obtenir les coordonnées de la souris (au clic suivant)"))
        self.MouseCoordinateLabel.setText(_translate("MainWindow", "Les coordonnées s\'afficheront ici"))
        self.setBoundsButton.setText(_translate("MainWindow", "Définir la taille du dessin"))
        self.widthLabel.setText(_translate("MainWindow", "Actuellement : Aucun."))
        self.drawButton.setText(_translate("MainWindow", "Dessine !"))
        self.errorLabel.setText(_translate("MainWindow", ""))

    def on_press(self, key):
        if key == Key.esc and self.drawingThread != None:
            self.exit_event.set()
    
    def setApp(self, value):
        self.app = value
        self.colors, self.coordinates = utils.getPalette(self.app)

    def setUrl(self, value):
        self.url = value

    def setSpeed(self, value):
        self.speed = value

    def setPixelInterval(self, value):
        self.pixelInterval = value
        self.skippedPixelsLabel.setText("Pixels ignorés : " + str(value))

    def setDither(self):
        self.dither = self.ditherBox.isChecked()

    def setIgnorePixel(self):
        self.ignorePixels = self.ignorePixelBox.isChecked()

    def setBounds(self):
        t = threading.Thread(target=self.setBoundsWorker)
        t.start()

    def setBoundsWorker(self):
        self.widthLabel.setText("En cours de selection...")
        self.MouseCoordinateLabel.adjustSize()
        bounds = utils.getBounds()
        self.width = abs(bounds[0][0] - bounds[1][0])
        self.height = abs(bounds[0][1] - bounds[1][1])
        self.startPosition = (bounds[0][0], bounds[0][1])
        self.widthLabel.setText(str(self.width) + ' x ' + str(self.height) + ' px')
    
    def displayMouseCoordinates(self):
        t = threading.Thread(target=self.displayMouseCoordinatesWorker)
        t.start()
    
    def displayMouseCoordinatesWorker(self):
        self.MouseCoordinateLabel.setText(str(utils.getNextMouseClickPositionCoordinates()))

    def draw(self):
        if self.url != "" and self.width != 0:
            self.exit_event = threading.Event()
            self.errorLabel.setText("")
            self.drawingThread = threading.Thread(target=self.drawWorker)
            self.drawingThread.start()
        else:
            if self.url == "":
                self.errorLabel.setText("J'ai besoin d'une URL")
            elif self.width == 0:
                self.errorLabel.setText("J'ai besoin de la largeur voulue")
    
    def drawWorker(self):
        try:
            draw = drawbot.DrawBot(self.width, self.height, self.startPosition, self.ignorePixels, self.dither, self.speed, self.pixelInterval, self.url, self.colors, self.coordinates)
            draw.draw(self.exit_event)
        except Exception as error:
            print(error)
            self.errorLabel.setText("L'URL n'est pas bonne ou pas une image")
            pass
        self.drawingThread = None

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
